# .goreleaser.yml
project_name: stacksmith

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/mubbie/stacksmith/cmd.Version={{.Version}} -X github.com/mubbie/stacksmith/cmd.BuildTime={{.Date}}
    binary: stacksmith

archives:
  - format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - scripts/stacksmith-lite.sh

brews:
  - name: mubbie/homebrew-tap
    homepage: https://github.com/mubbie/stacksmith
    description: Ultralight Artisan Git Stacking Tool
    license: MIT
    install: |
      bin.install "stacksmith"
      bash_completion.install "completions/stacksmith.bash" => "stacksmith"
      zsh_completion.install "completions/stacksmith.zsh" => "_stacksmith"
      fish_completion.install "completions/stacksmith.fish"

nfpms:
  - maintainer: Your Name <your.email@example.com>
    description: Ultralight Artisan Git Stacking Tool
    homepage: https://github.com/mubbie/stacksmith
    license: MIT
    formats:
      - deb
      - rpm